---
title: "LinearRegression_2"
author: "Sanmoy Paul"
date: "15 April 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Set Working Directory**
```{r setwd, echo=TRUE} 
setwd("C:/F/NMIMS/DataScience/Sem-2/MktngAnalytics/Project")
```

**Load Libraries**
```{r LoadLibraries, echo=TRUE}  
library(dplyr)
library(tidyr)
library(MASS)
library(caTools)
library(ISLR)
library(car)
library(ggplot2)
library(plotly)
library(gridExtra)
``` 

**Read Csv**
```{r readCSV, echo=TRUE}
regData<-read.csv("./data/Regression-Clean-Data.csv", header = TRUE, stringsAsFactors = FALSE)
regData<-regData[, 3:11]
```   

**Read First 6 recs**
```{r ReadFirst, echo=TRUE}
head(regData)
```
**Read Last 6 recs**
```{r ReadLast, echo=TRUE}
tail(regData)
```

**Structure of the data frame**
```{r struc, echo=TRUE}
str(regData)
glimpse(regData)
```

**No of Cols**
```{r nCol, echo=TRUE}
ncol(regData)
```

**No of rows**
```{r nRow, echo=TRUE}
nrow(regData)
```

**Names**
```{r colNames, echo=TRUE}
names(regData)
colnames(regData)
```  

**Detect NAs**
```{r detectNAs, echo=TRUE}
detectNAs<-function(x){
  return(sum(is.na(x)))
}
lapply(regData, detectNAs)
```  


**Summary stat**
```{r summaryStat, echo=TRUE}
summary(regData)
```  

**Convert into Fcators**
```{r convertFactors, echo=TRUE}
regData$City_Category<-as.factor(regData$City_Category)
regData$Parking<-as.factor(regData$Parking)
```

**Plots**
```{r plots, echo=TRUE}
p1<-ggplot(regData, aes(x=Dist_Hospital, y=House_Price)) + geom_point() + geom_smooth( method="lm", se=FALSE)+
  labs(title="Linear Relationship between Dist_Hospital and House_Price") +
  labs(x="Dist_Hospital") +
  labs(y="House_Price")

p2<-ggplot(regData, aes(x=Builtup, y=House_Price)) + geom_point() + geom_smooth( method="lm", se=FALSE)+
  labs(title="Linear Relationship between Education and House_Price") +
  labs(x="Builtup") +
  labs(y="House_Price")
grid.arrange(p1,p2, nrow=1, ncol=2)
```   

**Feature scaling**
```{r scaleData, echo=TRUE}
regData$Dist_Taxi<-scale(regData$Dist_Taxi)
regData$Dist_Market<-scale(regData$Dist_Market)
regData$Dist_Hospital<-scale(regData$Dist_Hospital)
regData$Carpet<-scale(regData$Carpet)
regData$Builtup<-scale(regData$Builtup)
regData$Rainfall<-scale(regData$Rainfall)
regData$House_Price<-scale(regData$House_Price)
```

**Split Data into Traind and Test Sets**
```{r splittingData, echo=TRUE}
set.seed(100)
split<-sample.split(regData$House_Price, SplitRatio=0.8)
trainSet<-subset(regData, split==TRUE)
testSet<-subset(regData, split==FALSE)  
```

**Model1**
```{r model1, echo=TRUE}
lm.fit1<-lm(House_Price~(Dist_Taxi+Dist_Market+Dist_Hospital+Carpet+Builtup+Rainfall), data=trainSet)
lm.fit1
summary(lm.fit1)
```

**Model2**
```{r model2, echo=TRUE}
lm.fit2<-lm(House_Price~(Dist_Market+Dist_Hospital+Carpet+Builtup+Rainfall), data=trainSet)
lm.fit2
summary(lm.fit2)
```

**Model3**
```{r model3, echo=TRUE}
lm.fit3<-lm(House_Price~(Dist_Market+Dist_Hospital+Carpet+Builtup), data=trainSet)
lm.fit3
summary(lm.fit3)
```

**Model4**
```{r model4, echo=TRUE}
lm.fit4<-lm(House_Price~(Dist_Market+Dist_Hospital+Builtup), data=trainSet)
lm.fit4
summary(lm.fit4)
```

**Model5**
```{r model5, echo=TRUE}
lm.fit5<-lm(House_Price~(Dist_Hospital+Builtup), data=trainSet)
lm.fit5
summary(lm.fit5)
```

**Prediction**
```{r prediction1, echo=TRUE}
predict1<-predict(lm.fit5, newdata = testSet)
predict1_df<-as.data.frame(predict1)
```



**Predicted Results**
```{r predictedResults, echo=TRUE}
lm._df<-data.frame(ActualHousePrice=testSet$House_Price, 
                   PredictedHousePrice=predict1_df$predict1)

lm._df
```